algoritmo "fahrenheit_para_celsius"
inicio var
   // Declarar as variáveis
   fahrenheit, celsius :real
inicio
   // Ler a temperatura em Fahrenheit
   escreva("Digite a temperatura em Fahrenheit: ")
   leia(fahrenheit)


   // Calcular a temperatura em Celsius
   celsius <- 5 / 9 * (fahrenheit - 32)


   // Exibir a temperatura em Celsius
   escreva("A temperatura em Celsius é: ", celsius)
fimalgoritmo

